### ISSUE TITLE
下载出错了

### ISSUE THREAD

**Issue by 0xCzer0** [renyijiu/douyin_downloader#13]
Traceback (most recent call last):
  File "douyin.py", line 539, in <module>
    CrawlerScheduler(content, favorite)
  File "douyin.py", line 341, in __init__
    self.scheduling(favorite)
  File "douyin.py", line 350, in scheduling
    self.download_user_videos(user_id, favorite)
  File "douyin.py", line 368, in download_user_videos
    self.push_download_job(uid, dytk, 0, favorite)
  File "douyin.py", line 379, in push_download_job
    list_json = get_list_by_uid(user_id, dytk, cursor, favorite)
  File "douyin.py", line 95, in get_list_by_uid
    signature = FREEZE_SIGNATURE if FREEZE_SIGNATURE else get_signature(user_id)
  File "douyin.py", line 70, in get_signature
    r.html.render()
  File "D:\Python\Python36\lib\site-packages\requests_html.py", line 654, in html
    self._html = HTML(session=self.session, url=self.url, html=self.content, default_encoding=self.encoding)
  File "D:\Python\Python36\lib\site-packages\requests_html.py", line 421, in __init__
    element=PyQuery(html)('html') or PyQuery(f'<html>{html}</html>')('html'),
  File "D:\Python\Python36\lib\site-packages\pyquery\pyquery.py", line 266, in __init__
    raise TypeError(context)
TypeError: None
他提到的requests_html和pyquery我重新卸载安装过，问题依旧，是哪出问题了？

**Comment by renyijiu** [comment]
@0xCzer0  你可以测试下requests_html是否能够正常执行？

**Comment by 0xCzer0** [comment]
跑了一段测试代码，requests_html可以正常执行
from requests_html import HTMLSession

session = HTMLSession()
r = session.get('https://www.qiushibaike.com/text/')
print(r.html.html)

**Comment by renyijiu** [comment]
@0xCzer0 换成r.html.render()试试

**Comment by 0xCzer0** [comment]
换了这个跑，可以正常下载
from requests_html import HTMLSession
session = HTMLSession()
r = session.get('https://www.qiushibaike.com/text/')
r.html.render()
#查看页面内容
print(r.html.html)

**Comment by j5465** [comment]
我也是这个问题，相同的报错信息
