### ISSUE TITLE
我得到这个错误。 请帮帮我

### ISSUE THREAD

**Issue by alexjim2985** [renyijiu/douyin_downloader#15]
Traceback (most recent call last):
  File "douyin.py", line 11, in <module>
    from requests_html import HTMLSession
  File "C:\Python\lib\site-packages\requests_html.py", line 9, in <module>
    import pyppeteer
  File "C:\Python\lib\site-packages\pyppeteer\__init__.py", line 30, in <module>
    from pyppeteer.launcher import connect, launch, executablePath  # noqa: E402
  File "C:\Python\lib\site-packages\pyppeteer\launcher.py", line 24, in <module>
    from pyppeteer.browser import Browser
  File "C:\Python\lib\site-packages\pyppeteer\browser.py", line 13, in <module>
    from pyppeteer.connection import Connection
  File "C:\Python\lib\site-packages\pyppeteer\connection.py", line 12, in <module>
    import websockets
  File "C:\Python\lib\site-packages\websockets\__init__.py", line 3, in <module>
    from .auth import *
  File "C:\Python\lib\site-packages\websockets\auth.py", line 15, in <module>
    from .server import HTTPResponse, WebSocketServerProtocol
  File "C:\Python\lib\site-packages\websockets\server.py", line 49, in <module>
    from .protocol import WebSocketCommonProtocol
  File "C:\Python\lib\site-packages\websockets\protocol.py", line 18, in <module>
    from typing import (
ImportError: cannot import name 'Deque'

**Comment by renyijiu** [comment]
请看下错误提示，执行搜索尝试一下。https://www.google.com/search?client=firefox-b-d&q=ImportError%3A+cannot+import+name+%27Deque%27
