### ISSUE TITLE
添加了链接无法下载东西

### ISSUE THREAD

**Issue by xyj155** [renyijiu/douyin_downloader#4]
我在里面添加了链接，但是下载的时候什么都没有

**Comment by renyijiu** [comment]
@xyj155 请提供下更为详细的信息，方便排查你的问题原因

**Comment by xyj155** [comment]
加qq细聊，方便吗？1789780841

**Comment by xyj155** [comment]
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/douyin/douyin.py", line 430, in <module>
    CrawlerScheduler(content, favorite)
  File "C:/Users/Administrator/Desktop/douyin/douyin.py", line 314, in __init__
    self.scheduling(favorite)
  File "C:/Users/Administrator/Desktop/douyin/douyin.py", line 323, in scheduling
    self.download_user_videos(user_id, favorite)
  File "C:/Users/Administrator/Desktop/douyin/douyin.py", line 335, in download_user_videos
    self.push_download_job(uid, dytk, 0, favorite)
  File "C:/Users/Administrator/Desktop/douyin/douyin.py", line 346, in push_download_job
    list_json = get_list_by_uid(user_id, dytk, cursor, favorite)
  File "C:/Users/Administrator/Desktop/douyin/douyin.py", line 90, in get_list_by_uid
    signature = FREEZE_SIGNATURE if FREEZE_SIGNATURE else get_signature(user_id)
  File "C:/Users/Administrator/Desktop/douyin/douyin.py", line 65, in get_signature
    r.html.render()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests_html.py", line 654, in html
    self._html = HTML(session=self.session, url=self.url, html=self.content, default_encoding=self.encoding)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests_html.py", line 421, in __init__
    element=PyQuery(html)('html') or PyQuery(f'<html>{html}</html>')('html'),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyquery\pyquery.py", line 266, in __init__
    raise TypeError(context)
TypeError: None

**Comment by renyijiu** [comment]
@xyj155 看着是你的requests_html没有正确执行，你可以单独测试下这个包是否能够正确执行，项目地址：https://github.com/psf/requests-html。另外推荐使用python3.6
