### ISSUE TITLE
无法一次下载一个账号的所有视频

### ISSUE THREAD

**Issue by cnscorpions** [renyijiu/douyin_downloader#9]
1. python douyin.py --urls="http://v.douyin.com/moUEXM/"
2. terminal中打印出

(douyin_env) F:\工作 2\一>python douyin.py --urls="http://v.douyin.com/moUEXM/"
Traceback (most recent call last):
  File "douyin.py", line 539, in <module>
    CrawlerScheduler(content, favorite)
  File "douyin.py", line 341, in __init__
    self.scheduling(favorite)
  File "douyin.py", line 350, in scheduling
    self.download_user_videos(user_id, favorite)
  File "douyin.py", line 368, in download_user_videos
    self.push_download_job(uid, dytk, 0, favorite)
  File "douyin.py", line 379, in push_download_job
    list_json = get_list_by_uid(user_id, dytk, cursor, favorite)
  File "douyin.py", line 95, in get_list_by_uid
    signature = FREEZE_SIGNATURE if FREEZE_SIGNATURE else get_signature(user_id)
  File "douyin.py", line 70, in get_signature
    r.html.render()
  File "F:\工作 2\一\douyin_env\lib\site-packages\requests_html.py", line 654, in html
    self._html = HTML(session=self.session, url=self.url, html=self.content, default_encoding=self.encoding)
  File "F:\工作 2\一\douyin_env\lib\site-packages\requests_html.py", line 421, in __init__
    element=PyQuery(html)('html') or PyQuery(f'<html>{html}</html>')('html'),
  File "F:\工作 2一\douyin_env\lib\site-packages\pyquery\pyquery.py", line 266, in __init__
    raise TypeError(context)
TypeError: None

3. python douyin.py -s -u 分享短链接/长链接 可以下载单个视频的

**Comment by renyijiu** [comment]
请确认依赖安装没有问题

**Comment by cnscorpions** [comment]
好的

[Gmail 编程邮箱 - Chat @ Spike](https://www.spikenow.com/?ref=spike-organic-signature&_ts=6m9gf)	[6m9gf]

On September 30, 2019 at 6:02 GMT, renyijiu <notifications@github.com> wrote:

请确认依赖安装没有问题
